framework:
  messenger:
    serializer:
      default_serializer: App\Messenger\ExternalJsonMessageSerializer
    transports:
      sqs_document:
        dsn: '%env(SQS_DOCUMENT_TRANSPORT_DSN)%'
        options:
          auto_setup: false
        failure_transport: sqs_document_dead_letter_queue
        retry_strategy:
          max_retries: 0

      sqs_document_dead_letter_queue:
        dsn: '%env(SQS_DOCUMENT_DLQ_TRANSPORT_DSN)%'
        options:
          auto_setup: false

      sqs_tests:
        dsn: '%env(SQS_TESTS_TRANSPORT_DSN)%'
        options:
          auto_setup: false
        failure_transport: sqs_tests_dead_letter_queue
        retry_strategy:
          max_retries: 0

      sqs_tests_dead_letter_queue:
        dsn: '%env(SQS_TESTS_DLQ_TRANSPORT_DSN)%'
        options:
          auto_setup: false

    routing:
      'App\Messenger\Message\CreateOpenApiDocument': sqs_document
      'App\Messenger\Message\CreateOpenApiTests': sqs_tests
