name: Deploy
on:
  push:
    branches: ['api-client/feature/post-document']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Create Sentry release for API Client
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          ignore_empty: true
          environment: api_client@prod

      - name: Create Sentry release for Open API Service
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          ignore_empty: true
          environment: openAPI-service@prod
